# Generated by Django 3.1.5 on 2021-02-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_employee',
            name='allowance',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='add_employee',
            name='basic_pay',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='add_employee',
            name='days_leave',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='add_employee',
            name='other_deductions',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='add_employee',
            name='overtime_hours',
            field=models.IntegerField(default=None),
        ),
    ]
