# Generated by Django 3.1.5 on 2021-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210212_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_employee',
            name='days_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='other_deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='add_employee',
            name='overtime_hours',
            field=models.IntegerField(default=0),
        ),
    ]
